common_words = [
    {"Spanish": "el", "English": ["the"]},
    {"Spanish": "la", "English": ["the"]},
    {"Spanish": "de", "English": ["of", "from"]},
    {"Spanish": "que", "English": ["that", "which"]},
    {"Spanish": "y", "English": ["and"]},
    {"Spanish": "a", "English": ["to", "at"]},
    {"Spanish": "en", "English": ["in", "on"]},
    {"Spanish": "un", "English": ["a", "an"]},
    {"Spanish": "una", "English": ["a", "an"]},
    {"Spanish": "ser", "English": ["to be"]},
    {"Spanish": "se", "English": ["oneself", "himself", "herself"]},
    {"Spanish": "no", "English": ["no"]},
    {"Spanish": "haber", "English": ["to have"]},
    {"Spanish": "por", "English": ["by", "through", "for"]},
    {"Spanish": "con", "English": ["with"]},
    {"Spanish": "para", "English": ["for", "to"]},
    {"Spanish": "como", "English": ["like", "as"]},
    {"Spanish": "estar", "English": ["to be"]},
    {"Spanish": "tener", "English": ["to have"]},
    {"Spanish": "le", "English": ["to him", "to her"]},
    {"Spanish": "lo", "English": ["it", "him"]},
    {"Spanish": "todo", "English": ["all", "everything"]},
    {"Spanish": "pero", "English": ["but"]},
    {"Spanish": "más", "English": ["more"]},
    {"Spanish": "hacer", "English": ["to do", "to make"]},
    {"Spanish": "o", "English": ["or"]},
    {"Spanish": "poder", "English": ["to be able", "can"]},
    {"Spanish": "decir", "English": ["to say", "to tell"]},
    {"Spanish": "este", "English": ["this"]},
    {"Spanish": "ir", "English": ["to go"]},
    {"Spanish": "otro", "English": ["other", "another"]},
    {"Spanish": "ese", "English": ["that"]},
    {"Spanish": "la", "English": ["her", "it"]},
    {"Spanish": "sí", "English": ["yes"]},
    {"Spanish": "me", "English": ["me", "myself"]},
    {"Spanish": "ya", "English": ["already", "now"]},
    {"Spanish": "ver", "English": ["to see"]},
    {"Spanish": "porque", "English": ["because"]},
    {"Spanish": "dar", "English": ["to give"]},
    {"Spanish": "cuando", "English": ["when"]},
    {"Spanish": "él", "English": ["he", "him"]},
    {"Spanish": "muy", "English": ["very"]},
    {"Spanish": "sin", "English": ["without"]},
    {"Spanish": "vez", "English": ["time", "instance"]},
    {"Spanish": "mucho", "English": ["much", "a lot"]},
    {"Spanish": "saber", "English": ["to know"]},
    {"Spanish": "qué", "English": ["what", "which"]},
    {"Spanish": "sobre", "English": ["on", "about"]},
    {"Spanish": "mi", "English": ["my"]},
    {"Spanish": "alguno", "English": ["some", "any"]},
    {"Spanish": "mismo", "English": ["same"]},
    {"Spanish": "yo", "English": ["I"]},
    {"Spanish": "también", "English": ["also", "too"]},
    {"Spanish": "hasta", "English": ["until"]},
    {"Spanish": "año", "English": ["year"]},
    {"Spanish": "dos", "English": ["two"]},
    {"Spanish": "querer", "English": ["to want"]},
    {"Spanish": "entre", "English": ["between", "among"]},
    {"Spanish": "así", "English": ["thus", "so"]},
    {"Spanish": "primero", "English": ["first"]},
    {"Spanish": "desde", "English": ["from", "since"]},
    {"Spanish": "grande", "English": ["big", "large"]},
    {"Spanish": "eso", "English": ["that"]},
    {"Spanish": "ni", "English": ["neither", "nor"]},
    {"Spanish": "nos", "English": ["us", "ourselves"]},
    {"Spanish": "llegar", "English": ["to arrive"]},
    {"Spanish": "pasar", "English": ["to pass", "to happen"]},
    {"Spanish": "tiempo", "English": ["time", "weather"]},
    {"Spanish": "ella", "English": ["she", "her"]},
    {"Spanish": "sí", "English": ["herself", "himself"]},
    {"Spanish": "día", "English": ["day"]},
    {"Spanish": "uno", "English": ["one"]},
    {"Spanish": "bien", "English": ["well"]},
    {"Spanish": "poco", "English": ["little", "few"]},
    {"Spanish": "deber", "English": ["to have to", "must", "should"]},
    {"Spanish": "entonces", "English": ["then"]},
    {"Spanish": "poner", "English": ["to put"]},
    {"Spanish": "cosa", "English": ["thing"]},
    {"Spanish": "tanto", "English": ["so much"]},
    {"Spanish": "hombre", "English": ["man"]},
    {"Spanish": "parecer", "English": ["to seem"]},
    {"Spanish": "nuestro", "English": ["our"]},
    {"Spanish": "tan", "English": ["so"]},
    {"Spanish": "donde", "English": ["where"]},
    {"Spanish": "ahora", "English": ["now"]},
    {"Spanish": "parte", "English": ["part"]},
    {"Spanish": "después", "English": ["after"]},
    {"Spanish": "vida", "English": ["life"]},
    {"Spanish": "quedar", "English": ["to stay", "to remain"]},
    {"Spanish": "siempre", "English": ["always"]},
    {"Spanish": "creer", "English": ["to believe"]},
    {"Spanish": "hablar", "English": ["to speak"]},
    {"Spanish": "llevar", "English": ["to carry", "to bring"]},
    {"Spanish": "dejar", "English": ["to leave", "to let"]},
    {"Spanish": "nada", "English": ["nothing"]},
    {"Spanish": "cada", "English": ["each", "every"]},
    {"Spanish": "seguir", "English": ["to follow", "to continue"]},
    {"Spanish": "menos", "English": ["less"]},
    {"Spanish": "nuevo", "English": ["new"]},
    {"Spanish": "encontrar", "English": ["to find"]}
]
